### ISSUE TITLE
Add source code

### ISSUE THREAD

**Issue by ThatOneCalculator** [drunckj/rog-rgb-control#1]
Not all of us are on debian based systems. Please make it so that we can build from source.

**Comment by MattMills** [comment]
There is none, this guy just wrote a bash script that downloads https://github.com/wroberts/rogauracore.git and builds it.

**Comment by drunckj** [comment]
Yea sorry I'll upload it today .

**Comment by MattMills** [comment]
You didn't actually add any source code, you just uploaded a binary file into a "src" directory...

**Comment by drunckj** [comment]
I actually lost the src and makefile . I'll be creating a new one again
from scratch.

**Comment by drunckj** [comment]
There was no gui for it. I clearly mentioned it needs rogauracore  to work.
